database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "YOUR_PASSWORD"
  dbname: "kitwork_db"
  ssl_mode: "disable"

server:
  port: 8081
  debug: false

smtp:
  host: "smtp.example.com"
  port: 587
  user: "user@example.com"
  password: "YOUR_SMTP_PASSWORD"
